#' Plot table from X-13ARIMA-SEATS seasonal adjustment run. 
#'
#' Generate plot of user-specified table from the output of a \code{seas} object generated by the \code{seasonal} package.
#'
#' Version 1.3, 2026-04-08
#'
#' @param seas_obj A seas object for a single series generated from the 
#'        \code{seasonal} package \insertCite{seasonal2018}{blstinyplot}.
#'        This is a required entry.
#' @param otl_col Character array of length 6; color used for different outliers, 
#'        with the order being \code{'ao','ls','tc','so','rp','tls'}. 
#'        Default is colors from the \code{RColorBrewer} palette \code{"Paired"} 
#'        \insertCite{RColorBrewer}{blstinyplot}.
#' @param add_sub_title Logical scalar; indicates if plots will include 
#'        subtitles denoting what series are plotted. 
#'        Default includes a subheader.
#' @param sub_title_cex Numeric scalar; scaling for main title of plot. 
#'        Default is \code{0.7}.
#' @return Outlier lines are added to an existing \code{tinyplot} plot.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @references
#'  \insertAllCited{}
#'
#' @examples
#' shoes_seas <-
#'     seasonal::seas(shoes2008, x11 = "", 
#'        transform.function = "log",
#'        regression.aictest = c("td", "easter"),
#'        outlier.types = "all",
#'        arima.model = "(0 1 1)(0 1 1)",
#'        forecast.maxlead = 60)
#' shoes_sa <- seasonal::final(shoes_seas)
#' plot_series(shoes_sa, 
#'      y_axis_label = "Shoes", 
#'      do_grid = TRUE,
#'      draw_recess = TRUE, 
#'      this_col = "black",
#'      start_plot = c(1958,1), 
#'      this_point_type = 1,
#'      main_title = "X-11 Adjustment for Shoe Store Sales",
#'      main_title_line = 1.5,
#'      main_title_cex = 1.0, 
#'      this_reset = TRUE)
#' add_outlier_lines(shoes_seas)
#' @importFrom Rdpack reprompt
#' @export
add_outlier_lines <- 
	function(seas_obj = NULL, 
		otl_col = NULL, 
		add_sub_title = TRUE, 
		sub_title_cex = 0.7) {
    # Author: Brian C. Monsell (OEUS) Version 1.3, 2026-04-08
	
    # check if a value is specified for \code{seas_obj}
  if (is.null(seas_obj)) {
    stop("must specify a seas object")
  } else {
  # check if a seas object is specified for \code{seas_obj}
    if (!inherits(seas_obj, "seas")) {
      stop("First argument must be a seas object")
    }
  }

  # if \code{otl_col} is NULL, generate colors from the \code{Paired} 
	# color palette
  if(is.null(otl_col)) {
	  otl_col <- RColorBrewer::brewer.pal(6, "Paired")
	}
	
  # inititalize outlier codes.
  all_otl <- c("ao", "ls", "tc", "so", "rp", "tls")
	
  i_otl <- 1:6
	
  # generate regressors, grab series frequency
  this_reg <- unlist(strsplit(get_reg_string(seas_obj), " "))
  this_freq <- seasonal::udg(seas_obj, "freq")
	
  # number of AO, LS, TC, SO, RP, and TLS outliers.
  nAO <- seasonal::udg(seas_obj, "outlier.ao")
  nLS <- seasonal::udg(seas_obj, "outlier.ls")
  nTC <- seasonal::udg(seas_obj, "outlier.tc")
  nSO <- seasonal::udg(seas_obj, "outlier.so")
  nRP <- seasonal::udg(seas_obj, "outlier.rp")
  nTLS <- seasonal::udg(seas_obj, "outlier.tls")
  
  # process each regressor.
  for (i in 1:length(this_reg)) {
        
    # set code for potential outliers
    if (tolower(substr(this_reg[i], 1, 3)) == "tls") {
      this_code <- "tls"
    } else {
      this_code <- tolower(substr(this_reg[i], 1, 2))
    }
      
    # check code to see if the regressor is an outlier
    if (sum(match(all_otl, this_code), na.rm = TRUE) > 0) {
    # process name of regressor to get outlier date(s)
      this_o <- proc_outlier(this_reg[i], this_freq)
      x_otlr <- this_o$year + (this_o$period - 1)/this_freq
    # ypos <- plotLim[4] - (plotLim[4] - plotLim[3])/30
      i_col <- i_otl[all_otl == this_code]
    # draw line for outlier
      if (this_code == "ls" | this_code == "rp" | this_code == "so" | 
          this_code == "tls") {
			  abline(v = x_otlr, lty = 2, col = otl_col[i_col])
			  if (this_code == "rp" | this_code == "tls") {
				  x_otlr <- this_o$year2 + (this_o$period2 - 1)/this_freq
				  abline(v = x_otlr, lty = 2, col = otl_col[i_col])
			  }
      } else {
			  abline(v = x_otlr, lty = 2, col = otl_col[i_col])
      }
    }
  }
	
	if (add_sub_title) {
    # create sub header for outliers included in plot
	  sub_header <- ""
	  if (nAO > 0) {
		  sub_header <- paste(sub_header, " AO = ", otl_col[1], sep = "")
		  if (nLS + nTC + nSO + nRP + nTLS > 0) {
			  sub_header <- paste(sub_header, ",", sep = "")
		  }
	  }
	  if (seasonal::udg(seas_obj, "outlier.ls") > 0) {
		  sub_header <- paste(sub_header, " LS = ", otl_col[2], sep = "")
		  if (nTC + nSO + nRP + nTLS > 0) {
			  sub_header <- paste(sub_header, ",", sep = "")
		  }
	  }
	  if (seasonal::udg(seas_obj, "outlier.tc") > 0) {
		  sub_header <- paste(sub_header, " TC = ", otl_col[3], sep = "")
		  if (nSO + nRP + nTLS > 0) {
			  sub_header <- paste(sub_header, ",", sep = "")
		  }
	  }
	  if (seasonal::udg(seas_obj, "outlier.so") > 0) {
		  sub_header <- paste(sub_header, " SO = ", otl_col[4], sep = "")
		  if (nRP + nTLS > 0) {
			  sub_header <- paste(sub_header, ",", sep = "")
		  }
	  }
	  if (seasonal::udg(seas_obj, "outlier.rp") > 0) {
		  sub_header <- paste(sub_header, " RP = ", otl_col[5], sep = "")
		  if (nTLS > 0) {
			  sub_header <- paste(sub_header, ",", sep = "")
		  }
	  }
	  if (seasonal::udg(seas_obj, "outlier.tls") > 0) {
		  sub_header <- paste(sub_header, " TLS = ", otl_col[6], sep = "")
	  }
  
  # print sub header for outliers included in plot
  	if (nchar(sub_header) > 0) {
	 		mtext(sub_header, 1, 2.5, cex = 0.75)
	  }
  }    
}
