#' Plot table from X-13ARIMA-SEATS seasonal adjustment run. 
#'
#' Generate plot of user-specified table from the output of a \code{seas} object 
#' generated by the \code{seasonal} package.
#'
#' Version 1.5, 2026-04-08
#'
#' @param seas_obj A seas object for a single series generated from the 
#'        \code{seasonal} package \insertCite{seasonal2018}{blstinyplot}.
#'        This is a required entry.
#' @param this_table Character string; X-13ARIMA-SEATS table name or abbreviation. 
#'        If not a valid table name, the function will print an error message and return a \code{NULL}.
#'        This entry is required.
#' @param main_title Character string; main title of plot.  
#'        Default is \code{'Cumulative periodogram'}.
#' @param main_title_line Integer scalar; position of main title of plot.  
#'        Default is \code{2.75}.
#' @param main_title_cex Numeric scalar; scaling for main title of plot. 
#'        Default is \code{this_plot_cex + 0.1}.
#' @param x_axis_label Character string; x-axis label for plot, if specified.
#' @param y_axis_label Character string; y-axis label for plot, if specified.
#' @param x_axis_main_ticks Numeric vector; X-axis tick marks.
#'        Default is determined by the \code{axis} function.
#' @param y_axis_main_ticks Numeric vector; Y-axis tick marks.
#'        Default is determined by the \code{axis} function.
#' @param y_limit Numeric vector of length 2; Range of values you wish 
#'        the plot to be plotted over. 
#'        Default is range of the series specified.
#' @param start_plot Integer vector of length 2; Starting date for plot. 
#'        Default is starting date for the time series. 
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines. 
#'        Default is no grid lines. 
#' @param draw_recess Logical scalar; indicates if certain plots will have 
#'        shaded areas for NBER recession dates \insertCite{nber}{blstinyplot}. 
#'        Default is no recession shading. 
#' @param recess_start numeric matrix; Rows of dates for additional recession 
#'        starting and ending dates. 
#'        Default is not to add recession dates.
#' @param recess_col Character string; color used for shading of recession region. 
#'        Default is \code{'lightgrey'}.
#' @param recess_sub Logical scalar; indicates if x-axis label for recession 
#'        is produced for this plot. 
#'        Default is x-axis label is produced
#' @param add_otl Logical scalar; indicates if lines for identified outliers 
#'        are included in series plots. 
#'        Default is not including lines for identified outliers. 
#' @param use_ratio Logical scalar; indicates if plots of seasonal factors, 
#'        irregular, and residuals are done as ratio plots. 
#'        Default has these plots as time series line plots.
#' @param add_sub_title Logical scalar; indicates if plots will include 
#'        subtitles denoting what series are plotted. 
#'        Default is not including subheaders.
#' @param sub_title_line Integer scalar; position of main title of plot.  
#'        Default is \code{1}.
#' @param sub_title_cex Numeric scalar; scaling for main title of plot. 
#'        Default is \code{this_plot_cex - 0.1}.
#' @param this_line_type Integer scalar; indicates line type of plot. 
#'        Default is \code{1}.
#' @param this_line_width Integer scalar; line width used for series.
#'        Default is \code{1}.
#' @param this_point_type Integer scalar; point type used for series. 
#'        Default is no points plotted.
#' @param this_col Character scalar; color used for plot. 
#'        Default is \code{'grey'}. 
#' @param otl_col Character array of length 6; color used for different 
#'        outliers, with the order being \code{'ao'}, \code{'ls'}, 
#'        \code{'tc'}, \code{'so'}, \code{'rp'}, \code{'tls'}. 
#'        Default is colors from the \code{RColorBrewer} palette \code{"Paired"} 
#'        \insertCite{RColorBrewer}{blstinyplot}.
#' @param this_plot_cex Numeric scalar; scaling for the plot itself. 
#'        Default is \code{0.8}.
#' @param this_lab_cex Numeric scalar; scaling for plot labels. 
#'        Default is the value of \code{this_plot_cex}.
#' @param this_axis_cex Numeric scalar; scaling for plot axis. 
#'        Default is the value of \code{this_plot_cex}.
#' @param this_mar Numeric vector; set margins for the plot. 
#'        Default is \code{c(4,4,4,0,5)}.
#' @param this_reset Logical scalar; if TRUE, the values of \code{par} are reset. 
#'        Default is \code{FALSE}.
#' @return Generate plot of user-specified series. If series not specified, 
#'         print out error message and return NULL.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @references
#'  \insertAllCited{}
#'
#' @examples
#' air_seas <- 
#'    seasonal::seas(AirPassengers, 
#'        arima.model = "(0 1 1)(0 1 1)",
#'        x11="", x11.save = c("e18"))
#' blstinyplot::plot_table(air_seas, "d11", 
#'          y_axis_label = "AirPassengers", 
#'          main_title = "X-11 Seasonal Adjustment of Airline Passengers",
#'          main_title_cex = 1.0, 
#'          add_sub_title = TRUE, 
#'          do_grid = TRUE, 
#'          draw_recess = TRUE, 
#'          use_ratio = FALSE,
#'          add_otl = TRUE,
#'          this_col = "black")
#' blstinyplot::plot_table(air_seas, "e18", 
#'          y_axis_label = "AirPassengers", 
#'          main_title = "Adjustment Factors of Airline Passengers",
#'          main_title_cex = 1.0, 
#'          add_sub_title = TRUE, 
#'          do_grid = TRUE, 
#'          draw_recess = TRUE, 
#'          use_ratio = TRUE,
#'          add_otl = TRUE,
#'          this_col = "darkblue")
#' @import graphics
#' @import stats
#' @importFrom Rdpack reprompt
#' @export
plot_table <- 
	function(seas_obj = NULL, 
		this_table = NULL, 
		main_title = NULL, 
		main_title_line = 2, 
		main_title_cex = 1.25,
		x_axis_label = NULL, 
		y_axis_label = NULL, 
		x_axis_main_ticks = NULL,
		y_axis_main_ticks = NULL,
		y_limit = NULL, 
		start_plot = NULL, 
		do_grid = FALSE, 
		draw_recess = FALSE, 
		recess_start = NULL, 
		recess_col = NULL, 
		recess_sub = TRUE, 
		add_otl = FALSE, 
		use_ratio = FALSE, 
		add_sub_title = FALSE, 
		sub_title_line = 1, 
		sub_title_cex = NULL, 
		this_line_type = NULL, 
		this_line_width = 1,
		this_point_type = NULL, 
		this_col = "grey", 
		otl_col = NULL,
		this_plot_cex = 0.8, 
		this_lab_cex = NULL, 
		this_axis_cex = NULL, 
		this_mar = c(4,4,4,0.5), 
		this_reset = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 1.5, 2026-04-08
    
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            stop("First argument must be a seas object")
        }
    }
    
    # check if a value is specified for \code{this_table}
    if (is.null(this_table)) {
      stop("must specify tables to plot")
    }
	
	# if \code{this_reset} is TRUE, set \code{old_par}
	  if (this_reset) {
	    old_par <- par(no.readonly = TRUE)
	  }
    
  # set cex values if not set by user
    if (is.null(this_lab_cex)) {
        this_lab_cex <- this_plot_cex
    }
    if (is.null(this_axis_cex)) {
        this_axis_cex <- this_plot_cex
    }
    if (is.null(main_title_cex)) {
        main_title_cex <- this_plot_cex + 0.1
    }
    if (is.null(sub_title_cex)) {
        sub_title_cex <- this_plot_cex - 0.1
    }

  # reset par based on user input.
    par(mar = this_mar, cex = this_plot_cex, cex.axis = this_axis_cex,
        cex.lab = this_lab_cex)
        
    if (is.null(main_title)) {
        if (add_sub_title) {
            add_sub_title <- FALSE
            warning("Since main_title = NULL, the add_sub_title argument is set to FALSE.")
        }
    }

    # Extract series from the X-13 output - if series not supported, 
    # print out error message and return NULL
	
    this_series <- 
		tryCatch(seasonal::series(seas_obj, this_table), error = function(e) {
			print(paste("series not valid:", this_table))
			NULL
    })
    
    if (is.null(this_series)) {
        return()
    }
    
    if (is.null(y_limit)) {
        y_limit <- range(this_series)
    }
    
    if (is.null(this_line_type)) {
        this_line_type = 1
    }
    
    # Get transformation, then set value of factor mean.
    this_trans <- seasonal::udg(seas_obj, "transform")
    if (this_trans == "Automatic selection") {
        this_trans <- seasonal::udg(seas_obj, "aictrans")
    }
		
    # Check to see if this is a ratio plot.
    if (use_ratio) {
      if (this_trans == "Log(y)") {
        h_bar <- 1
      } else {
        h_bar <- 0
      }

		# If start_plot specified, shorten series
      if (!is.null(start_plot)) {
		    this_series <- window(this_series, start = start_plot)
		  }
    
        # Generate ratio plot.
      plot_ratio(ratio_series = this_series,
            ratio_range = y_limit,
            ratio_color = this_col, 
            main_title = main_title, 
            main_title_line = main_title_line, 
            main_title_cex = main_title_cex,
            x_axis_main_ticks = x_axis_main_ticks,
            y_axis_main_ticks = y_axis_main_ticks,
            y_axis_label = y_axis_label,
            this_plot_cex = this_plot_cex, 
            this_lab_cex = this_lab_cex,
            this_axis_cex = this_axis_cex, 
            this_mar = this_mar, 
            ratio_mean_color = this_col,
            ratio_mean = h_bar)            
	
	# add grid.
      if (do_grid) {
        grid()
      }
    
		# add shaded regions for recessions.
		  if (draw_recess) {
			  draw_recession(recess_col, 
			                 this_add_recess_start = recess_start, 
			                 this_sub_recess = recess_sub, 
			                 this_sub_line = 3) 
		  }
    
    } else {
        # Generate plot with title.
	    plot_series(this_series = this_series, 
            main_title = main_title, 
            main_title_line = main_title_line, 
            main_title_cex = main_title_cex,
            x_axis_label = x_axis_label, 
            y_axis_label = y_axis_label, 
            x_axis_main_ticks = x_axis_main_ticks,
            y_axis_main_ticks = y_axis_main_ticks,
            y_limit = y_limit, 
            start_plot = start_plot, 
            do_grid = do_grid,
            draw_recess = draw_recess, 
            recess_start = recess_start, 
            recess_col = recess_col, 
            recess_sub = recess_sub,
            this_trans = this_trans, 
            use_ratio = FALSE, 
            this_col = this_col, 
            this_line_type = this_line_type,
            this_line_width = this_line_type,
            this_point_type = this_point_type, 
            this_plot_cex = this_plot_cex, 
            this_lab_cex = this_lab_cex,
            this_axis_cex = this_axis_cex, 
            this_mar = this_mar, 
            this_reset = this_reset)
    }

    # add subtitle.
    if (add_sub_title) {
      this_sub_title <- 
		    paste(this_table, " = ", this_col[1], sep = "")
      mtext(this_sub_title, 3, sub_title_line, cex = sub_title_cex)
    }
    
	# add lines for outliers.
    if (add_otl) {
		  add_outlier_lines(seas_obj, 
		                    otl_col, 
		                    add_sub_title, 
		                    sub_title_cex)
    }
    if (this_reset) { reset_par(old_par) }
    
}
